version: '3.7'

################################################################################
# Database notes
#  * any sql in the ./sql folder will be imported
#  * to reimport sql from ./sql, delete persistent volume `docker-compose down -v`
#  * there is a "_post_processing.sql" file in /sql that add local specific entries
#    -the address must be changes if using a different port than the default (3000)

services:

  mysql:
    container_name: om_mysql
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER:          ${MYSQL_USER:-user}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE:      ${MYSQL_DATABASE:-wordpress}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  wordpress:
    container_name: om_wordpress
    image: om_wordpress
    build:
      dockerfile: Dockerfile-wordpress
      context: ./
    depends_on:
      - mysql
    links:
      - mysql:om_mysql
    restart: always
    environment:
      WORDPRESS_DEBUG:        ${WORDPRESS_DEBUG:-0}
      WORDPRESS_DB_HOST:      ${WORDPRESS_DB_HOST:-mysql}
    volumes:
      - ./onemission:/var/www
      - ${PHP_CONF_DIR-./config/php-fpm}:/usr/local/etc/php-fpm.d
      - ${PHP_LOG_DIR:-./logs/php-fpm}:/usr/local/var/log/php-fpm

  nginx:
    container_name: om_nginx
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - ${WORDPRESS_PORT:-8080}:80
      - 443:443
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ${NGINX_CONF_DIR:-./config/nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt

  phpmyadmin:
    container_name: om_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:om_mysql
    ports:
      - ${PHPMYADMIN_PORT:-8000}:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}

  wp-cli:
    image: wordpress:cli-${WP_CLI_VERSION:-2.2.0}-php${PHP_VERSION:-7.3}
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - mysql
      - wordpress
    volumes:
      - ./onemission/public:/var/www/public:rw
      # - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
      # - .:/var/www/html/wp-content/plugins/my-plugin:ro

  # certbot:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: om_certbot
  #   volumes:
  #     - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
  #     - ${WORDPRESS_DATA_DIR}:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email ${SSL_CERT_EMAIL:-user@example.com} --agree-tos --no-eff-email --staging -d ${SSL_DOMAIN} -d www.${SSL_DOMAIN}

volumes:
  db_data:
