---
- name: dump mysql database from live server
  hosts: kinsta
  vars:
    - db_exclude:
      - "Database"
      - "information_schema"
      - "performance_schema"
      - "mysql"
  tasks:
    - name: get db names
      shell: 'mysql -u {{ db_user }} -p{{ db_password }} -e "show databases;" '
      register: dblist
    - name: make live dump directory '{{ db_dump_live }}'
      file:
        path: "{{ db_dump_live }}"
        state: directory
        mode: 0755
    - name: dump live databases
      mysql_db:
        state: dump
        name: "{{ item }}"
        target: "{{ db_dump_live }}/{{ item }}.sql"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
      with_items: "{{ dblist.stdout_lines | difference(db_exclude) }}"

- name: transfer sql to staging site
  hosts: kinsta-stage
  tasks:
    - name: make staging dump directory '{{ db_dump_stage }}'
      file:
        path: "{{ db_dump_stage }}"
        state: directory
        mode: 0755
    - name: copy the database to staging site
      delegate_to: kinsta
      synchronize:
        src: "{{ db_dump_live }}"
        # hostvars[inventory_hostname].ansible_ssh_host
        dest: "{{ db_dump_stage }}/.."
        recursive: yes
        rsync_opts:
          - "-e ssh -p 58824"
    # - name: remove live database dumps
    #   file:
    #     path: "{{ db_dump_live }}"
    #     state: absent
    # - name: import the database
    #   mysql_db:
    #     name: wordpress
    #     state: import
    #     target: /home/vagrant/wordpress.sql
    #     login_host: 192.168.0.69
    #     login_user: root
    #     login_password: '123456'
    #   delegate_to: neo_development
    #  - name: apply staging-only db changes
    #    turn query monitor on
    #  - name: copy uploads to staging site
